// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdcp_lte_state_t.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pdcp_5flte_5fstate_5ft_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pdcp_5flte_5fstate_5ft_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pdcp_5flte_5fstate_5ft_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pdcp_5flte_5fstate_5ft_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pdcp_5flte_5fstate_5ft_2eproto;
namespace fs {
namespace pdcp_rrc {
class pdcp_lte_state_t;
class pdcp_lte_state_tDefaultTypeInternal;
extern pdcp_lte_state_tDefaultTypeInternal _pdcp_lte_state_t_default_instance_;
}  // namespace pdcp_rrc
}  // namespace fs
PROTOBUF_NAMESPACE_OPEN
template<> ::fs::pdcp_rrc::pdcp_lte_state_t* Arena::CreateMaybeMessage<::fs::pdcp_rrc::pdcp_lte_state_t>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fs {
namespace pdcp_rrc {

// ===================================================================

class pdcp_lte_state_t PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fs.pdcp_rrc.pdcp_lte_state_t) */ {
 public:
  inline pdcp_lte_state_t() : pdcp_lte_state_t(nullptr) {};
  virtual ~pdcp_lte_state_t();

  pdcp_lte_state_t(const pdcp_lte_state_t& from);
  pdcp_lte_state_t(pdcp_lte_state_t&& from) noexcept
    : pdcp_lte_state_t() {
    *this = ::std::move(from);
  }

  inline pdcp_lte_state_t& operator=(const pdcp_lte_state_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline pdcp_lte_state_t& operator=(pdcp_lte_state_t&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const pdcp_lte_state_t& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const pdcp_lte_state_t* internal_default_instance() {
    return reinterpret_cast<const pdcp_lte_state_t*>(
               &_pdcp_lte_state_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(pdcp_lte_state_t& a, pdcp_lte_state_t& b) {
    a.Swap(&b);
  }
  inline void Swap(pdcp_lte_state_t* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(pdcp_lte_state_t* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline pdcp_lte_state_t* New() const final {
    return CreateMaybeMessage<pdcp_lte_state_t>(nullptr);
  }

  pdcp_lte_state_t* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<pdcp_lte_state_t>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const pdcp_lte_state_t& from);
  void MergeFrom(const pdcp_lte_state_t& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(pdcp_lte_state_t* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fs.pdcp_rrc.pdcp_lte_state_t";
  }
  protected:
  explicit pdcp_lte_state_t(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_pdcp_5flte_5fstate_5ft_2eproto);
    return ::descriptor_table_pdcp_5flte_5fstate_5ft_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNextPdcpTxSnFieldNumber = 1,
    kTxHfnFieldNumber = 2,
    kRxHfnFieldNumber = 3,
    kNextPdcpRxSnFieldNumber = 4,
    kLastSubmittedPdcpRxSnFieldNumber = 5,
    kReorderingPdcpRxCountFieldNumber = 6,
  };
  // uint32 next_pdcp_tx_sn = 1;
  void clear_next_pdcp_tx_sn();
  ::PROTOBUF_NAMESPACE_ID::uint32 next_pdcp_tx_sn() const;
  void set_next_pdcp_tx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_next_pdcp_tx_sn() const;
  void _internal_set_next_pdcp_tx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 tx_hfn = 2;
  void clear_tx_hfn();
  ::PROTOBUF_NAMESPACE_ID::uint32 tx_hfn() const;
  void set_tx_hfn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_tx_hfn() const;
  void _internal_set_tx_hfn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 rx_hfn = 3;
  void clear_rx_hfn();
  ::PROTOBUF_NAMESPACE_ID::uint32 rx_hfn() const;
  void set_rx_hfn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rx_hfn() const;
  void _internal_set_rx_hfn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 next_pdcp_rx_sn = 4;
  void clear_next_pdcp_rx_sn();
  ::PROTOBUF_NAMESPACE_ID::uint32 next_pdcp_rx_sn() const;
  void set_next_pdcp_rx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_next_pdcp_rx_sn() const;
  void _internal_set_next_pdcp_rx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 last_submitted_pdcp_rx_sn = 5;
  void clear_last_submitted_pdcp_rx_sn();
  ::PROTOBUF_NAMESPACE_ID::uint32 last_submitted_pdcp_rx_sn() const;
  void set_last_submitted_pdcp_rx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_last_submitted_pdcp_rx_sn() const;
  void _internal_set_last_submitted_pdcp_rx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 reordering_pdcp_rx_count = 6;
  void clear_reordering_pdcp_rx_count();
  ::PROTOBUF_NAMESPACE_ID::uint32 reordering_pdcp_rx_count() const;
  void set_reordering_pdcp_rx_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_reordering_pdcp_rx_count() const;
  void _internal_set_reordering_pdcp_rx_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:fs.pdcp_rrc.pdcp_lte_state_t)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 next_pdcp_tx_sn_;
  ::PROTOBUF_NAMESPACE_ID::uint32 tx_hfn_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rx_hfn_;
  ::PROTOBUF_NAMESPACE_ID::uint32 next_pdcp_rx_sn_;
  ::PROTOBUF_NAMESPACE_ID::uint32 last_submitted_pdcp_rx_sn_;
  ::PROTOBUF_NAMESPACE_ID::uint32 reordering_pdcp_rx_count_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_pdcp_5flte_5fstate_5ft_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// pdcp_lte_state_t

// uint32 next_pdcp_tx_sn = 1;
inline void pdcp_lte_state_t::clear_next_pdcp_tx_sn() {
  next_pdcp_tx_sn_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::_internal_next_pdcp_tx_sn() const {
  return next_pdcp_tx_sn_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::next_pdcp_tx_sn() const {
  // @@protoc_insertion_point(field_get:fs.pdcp_rrc.pdcp_lte_state_t.next_pdcp_tx_sn)
  return _internal_next_pdcp_tx_sn();
}
inline void pdcp_lte_state_t::_internal_set_next_pdcp_tx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  next_pdcp_tx_sn_ = value;
}
inline void pdcp_lte_state_t::set_next_pdcp_tx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_next_pdcp_tx_sn(value);
  // @@protoc_insertion_point(field_set:fs.pdcp_rrc.pdcp_lte_state_t.next_pdcp_tx_sn)
}

// uint32 tx_hfn = 2;
inline void pdcp_lte_state_t::clear_tx_hfn() {
  tx_hfn_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::_internal_tx_hfn() const {
  return tx_hfn_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::tx_hfn() const {
  // @@protoc_insertion_point(field_get:fs.pdcp_rrc.pdcp_lte_state_t.tx_hfn)
  return _internal_tx_hfn();
}
inline void pdcp_lte_state_t::_internal_set_tx_hfn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  tx_hfn_ = value;
}
inline void pdcp_lte_state_t::set_tx_hfn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_tx_hfn(value);
  // @@protoc_insertion_point(field_set:fs.pdcp_rrc.pdcp_lte_state_t.tx_hfn)
}

// uint32 rx_hfn = 3;
inline void pdcp_lte_state_t::clear_rx_hfn() {
  rx_hfn_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::_internal_rx_hfn() const {
  return rx_hfn_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::rx_hfn() const {
  // @@protoc_insertion_point(field_get:fs.pdcp_rrc.pdcp_lte_state_t.rx_hfn)
  return _internal_rx_hfn();
}
inline void pdcp_lte_state_t::_internal_set_rx_hfn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rx_hfn_ = value;
}
inline void pdcp_lte_state_t::set_rx_hfn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rx_hfn(value);
  // @@protoc_insertion_point(field_set:fs.pdcp_rrc.pdcp_lte_state_t.rx_hfn)
}

// uint32 next_pdcp_rx_sn = 4;
inline void pdcp_lte_state_t::clear_next_pdcp_rx_sn() {
  next_pdcp_rx_sn_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::_internal_next_pdcp_rx_sn() const {
  return next_pdcp_rx_sn_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::next_pdcp_rx_sn() const {
  // @@protoc_insertion_point(field_get:fs.pdcp_rrc.pdcp_lte_state_t.next_pdcp_rx_sn)
  return _internal_next_pdcp_rx_sn();
}
inline void pdcp_lte_state_t::_internal_set_next_pdcp_rx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  next_pdcp_rx_sn_ = value;
}
inline void pdcp_lte_state_t::set_next_pdcp_rx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_next_pdcp_rx_sn(value);
  // @@protoc_insertion_point(field_set:fs.pdcp_rrc.pdcp_lte_state_t.next_pdcp_rx_sn)
}

// uint32 last_submitted_pdcp_rx_sn = 5;
inline void pdcp_lte_state_t::clear_last_submitted_pdcp_rx_sn() {
  last_submitted_pdcp_rx_sn_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::_internal_last_submitted_pdcp_rx_sn() const {
  return last_submitted_pdcp_rx_sn_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::last_submitted_pdcp_rx_sn() const {
  // @@protoc_insertion_point(field_get:fs.pdcp_rrc.pdcp_lte_state_t.last_submitted_pdcp_rx_sn)
  return _internal_last_submitted_pdcp_rx_sn();
}
inline void pdcp_lte_state_t::_internal_set_last_submitted_pdcp_rx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  last_submitted_pdcp_rx_sn_ = value;
}
inline void pdcp_lte_state_t::set_last_submitted_pdcp_rx_sn(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_last_submitted_pdcp_rx_sn(value);
  // @@protoc_insertion_point(field_set:fs.pdcp_rrc.pdcp_lte_state_t.last_submitted_pdcp_rx_sn)
}

// uint32 reordering_pdcp_rx_count = 6;
inline void pdcp_lte_state_t::clear_reordering_pdcp_rx_count() {
  reordering_pdcp_rx_count_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::_internal_reordering_pdcp_rx_count() const {
  return reordering_pdcp_rx_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 pdcp_lte_state_t::reordering_pdcp_rx_count() const {
  // @@protoc_insertion_point(field_get:fs.pdcp_rrc.pdcp_lte_state_t.reordering_pdcp_rx_count)
  return _internal_reordering_pdcp_rx_count();
}
inline void pdcp_lte_state_t::_internal_set_reordering_pdcp_rx_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  reordering_pdcp_rx_count_ = value;
}
inline void pdcp_lte_state_t::set_reordering_pdcp_rx_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_reordering_pdcp_rx_count(value);
  // @@protoc_insertion_point(field_set:fs.pdcp_rrc.pdcp_lte_state_t.reordering_pdcp_rx_count)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pdcp_rrc
}  // namespace fs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pdcp_5flte_5fstate_5ft_2eproto
