// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdcp_lte_state_t.proto

#include "srsenb/hdr/funsplit_proto/pdcp_lte_state_t.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace fs {
namespace pdcp_rrc {
class pdcp_lte_state_tDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<pdcp_lte_state_t> _instance;
} _pdcp_lte_state_t_default_instance_;
}  // namespace pdcp_rrc
}  // namespace fs
static void InitDefaultsscc_info_pdcp_lte_state_t_pdcp_5flte_5fstate_5ft_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fs::pdcp_rrc::_pdcp_lte_state_t_default_instance_;
    new (ptr) ::fs::pdcp_rrc::pdcp_lte_state_t();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fs::pdcp_rrc::pdcp_lte_state_t::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_pdcp_lte_state_t_pdcp_5flte_5fstate_5ft_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_pdcp_lte_state_t_pdcp_5flte_5fstate_5ft_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_pdcp_5flte_5fstate_5ft_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_pdcp_5flte_5fstate_5ft_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_pdcp_5flte_5fstate_5ft_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_pdcp_5flte_5fstate_5ft_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::fs::pdcp_rrc::pdcp_lte_state_t, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::fs::pdcp_rrc::pdcp_lte_state_t, next_pdcp_tx_sn_),
  PROTOBUF_FIELD_OFFSET(::fs::pdcp_rrc::pdcp_lte_state_t, tx_hfn_),
  PROTOBUF_FIELD_OFFSET(::fs::pdcp_rrc::pdcp_lte_state_t, rx_hfn_),
  PROTOBUF_FIELD_OFFSET(::fs::pdcp_rrc::pdcp_lte_state_t, next_pdcp_rx_sn_),
  PROTOBUF_FIELD_OFFSET(::fs::pdcp_rrc::pdcp_lte_state_t, last_submitted_pdcp_rx_sn_),
  PROTOBUF_FIELD_OFFSET(::fs::pdcp_rrc::pdcp_lte_state_t, reordering_pdcp_rx_count_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::fs::pdcp_rrc::pdcp_lte_state_t)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::fs::pdcp_rrc::_pdcp_lte_state_t_default_instance_),
};

const char descriptor_table_protodef_pdcp_5flte_5fstate_5ft_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026pdcp_lte_state_t.proto\022\013fs.pdcp_rrc\"\251\001"
  "\n\020pdcp_lte_state_t\022\027\n\017next_pdcp_tx_sn\030\001 "
  "\001(\r\022\016\n\006tx_hfn\030\002 \001(\r\022\016\n\006rx_hfn\030\003 \001(\r\022\027\n\017n"
  "ext_pdcp_rx_sn\030\004 \001(\r\022!\n\031last_submitted_p"
  "dcp_rx_sn\030\005 \001(\r\022 \n\030reordering_pdcp_rx_co"
  "unt\030\006 \001(\rb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_pdcp_5flte_5fstate_5ft_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_pdcp_5flte_5fstate_5ft_2eproto_sccs[1] = {
  &scc_info_pdcp_lte_state_t_pdcp_5flte_5fstate_5ft_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_pdcp_5flte_5fstate_5ft_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pdcp_5flte_5fstate_5ft_2eproto = {
  false, false, descriptor_table_protodef_pdcp_5flte_5fstate_5ft_2eproto, "pdcp_lte_state_t.proto", 217,
  &descriptor_table_pdcp_5flte_5fstate_5ft_2eproto_once, descriptor_table_pdcp_5flte_5fstate_5ft_2eproto_sccs, descriptor_table_pdcp_5flte_5fstate_5ft_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_pdcp_5flte_5fstate_5ft_2eproto::offsets,
  file_level_metadata_pdcp_5flte_5fstate_5ft_2eproto, 1, file_level_enum_descriptors_pdcp_5flte_5fstate_5ft_2eproto, file_level_service_descriptors_pdcp_5flte_5fstate_5ft_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_pdcp_5flte_5fstate_5ft_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_pdcp_5flte_5fstate_5ft_2eproto)), true);
namespace fs {
namespace pdcp_rrc {

// ===================================================================

void pdcp_lte_state_t::InitAsDefaultInstance() {
}
class pdcp_lte_state_t::_Internal {
 public:
};

pdcp_lte_state_t::pdcp_lte_state_t(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:fs.pdcp_rrc.pdcp_lte_state_t)
}
pdcp_lte_state_t::pdcp_lte_state_t(const pdcp_lte_state_t& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&next_pdcp_tx_sn_, &from.next_pdcp_tx_sn_,
    static_cast<size_t>(reinterpret_cast<char*>(&reordering_pdcp_rx_count_) -
    reinterpret_cast<char*>(&next_pdcp_tx_sn_)) + sizeof(reordering_pdcp_rx_count_));
  // @@protoc_insertion_point(copy_constructor:fs.pdcp_rrc.pdcp_lte_state_t)
}

void pdcp_lte_state_t::SharedCtor() {
  ::memset(&next_pdcp_tx_sn_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&reordering_pdcp_rx_count_) -
      reinterpret_cast<char*>(&next_pdcp_tx_sn_)) + sizeof(reordering_pdcp_rx_count_));
}

pdcp_lte_state_t::~pdcp_lte_state_t() {
  // @@protoc_insertion_point(destructor:fs.pdcp_rrc.pdcp_lte_state_t)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void pdcp_lte_state_t::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void pdcp_lte_state_t::ArenaDtor(void* object) {
  pdcp_lte_state_t* _this = reinterpret_cast< pdcp_lte_state_t* >(object);
  (void)_this;
}
void pdcp_lte_state_t::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void pdcp_lte_state_t::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const pdcp_lte_state_t& pdcp_lte_state_t::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_pdcp_lte_state_t_pdcp_5flte_5fstate_5ft_2eproto.base);
  return *internal_default_instance();
}


void pdcp_lte_state_t::Clear() {
// @@protoc_insertion_point(message_clear_start:fs.pdcp_rrc.pdcp_lte_state_t)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&next_pdcp_tx_sn_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&reordering_pdcp_rx_count_) -
      reinterpret_cast<char*>(&next_pdcp_tx_sn_)) + sizeof(reordering_pdcp_rx_count_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* pdcp_lte_state_t::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 next_pdcp_tx_sn = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          next_pdcp_tx_sn_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 tx_hfn = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          tx_hfn_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 rx_hfn = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          rx_hfn_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 next_pdcp_rx_sn = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          next_pdcp_rx_sn_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 last_submitted_pdcp_rx_sn = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          last_submitted_pdcp_rx_sn_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 reordering_pdcp_rx_count = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          reordering_pdcp_rx_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* pdcp_lte_state_t::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fs.pdcp_rrc.pdcp_lte_state_t)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 next_pdcp_tx_sn = 1;
  if (this->next_pdcp_tx_sn() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_next_pdcp_tx_sn(), target);
  }

  // uint32 tx_hfn = 2;
  if (this->tx_hfn() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_tx_hfn(), target);
  }

  // uint32 rx_hfn = 3;
  if (this->rx_hfn() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_rx_hfn(), target);
  }

  // uint32 next_pdcp_rx_sn = 4;
  if (this->next_pdcp_rx_sn() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_next_pdcp_rx_sn(), target);
  }

  // uint32 last_submitted_pdcp_rx_sn = 5;
  if (this->last_submitted_pdcp_rx_sn() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_last_submitted_pdcp_rx_sn(), target);
  }

  // uint32 reordering_pdcp_rx_count = 6;
  if (this->reordering_pdcp_rx_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_reordering_pdcp_rx_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fs.pdcp_rrc.pdcp_lte_state_t)
  return target;
}

size_t pdcp_lte_state_t::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fs.pdcp_rrc.pdcp_lte_state_t)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 next_pdcp_tx_sn = 1;
  if (this->next_pdcp_tx_sn() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_next_pdcp_tx_sn());
  }

  // uint32 tx_hfn = 2;
  if (this->tx_hfn() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_tx_hfn());
  }

  // uint32 rx_hfn = 3;
  if (this->rx_hfn() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_rx_hfn());
  }

  // uint32 next_pdcp_rx_sn = 4;
  if (this->next_pdcp_rx_sn() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_next_pdcp_rx_sn());
  }

  // uint32 last_submitted_pdcp_rx_sn = 5;
  if (this->last_submitted_pdcp_rx_sn() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_last_submitted_pdcp_rx_sn());
  }

  // uint32 reordering_pdcp_rx_count = 6;
  if (this->reordering_pdcp_rx_count() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_reordering_pdcp_rx_count());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void pdcp_lte_state_t::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fs.pdcp_rrc.pdcp_lte_state_t)
  GOOGLE_DCHECK_NE(&from, this);
  const pdcp_lte_state_t* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<pdcp_lte_state_t>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fs.pdcp_rrc.pdcp_lte_state_t)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fs.pdcp_rrc.pdcp_lte_state_t)
    MergeFrom(*source);
  }
}

void pdcp_lte_state_t::MergeFrom(const pdcp_lte_state_t& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fs.pdcp_rrc.pdcp_lte_state_t)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.next_pdcp_tx_sn() != 0) {
    _internal_set_next_pdcp_tx_sn(from._internal_next_pdcp_tx_sn());
  }
  if (from.tx_hfn() != 0) {
    _internal_set_tx_hfn(from._internal_tx_hfn());
  }
  if (from.rx_hfn() != 0) {
    _internal_set_rx_hfn(from._internal_rx_hfn());
  }
  if (from.next_pdcp_rx_sn() != 0) {
    _internal_set_next_pdcp_rx_sn(from._internal_next_pdcp_rx_sn());
  }
  if (from.last_submitted_pdcp_rx_sn() != 0) {
    _internal_set_last_submitted_pdcp_rx_sn(from._internal_last_submitted_pdcp_rx_sn());
  }
  if (from.reordering_pdcp_rx_count() != 0) {
    _internal_set_reordering_pdcp_rx_count(from._internal_reordering_pdcp_rx_count());
  }
}

void pdcp_lte_state_t::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fs.pdcp_rrc.pdcp_lte_state_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void pdcp_lte_state_t::CopyFrom(const pdcp_lte_state_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fs.pdcp_rrc.pdcp_lte_state_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool pdcp_lte_state_t::IsInitialized() const {
  return true;
}

void pdcp_lte_state_t::InternalSwap(pdcp_lte_state_t* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(pdcp_lte_state_t, reordering_pdcp_rx_count_)
      + sizeof(pdcp_lte_state_t::reordering_pdcp_rx_count_)
      - PROTOBUF_FIELD_OFFSET(pdcp_lte_state_t, next_pdcp_tx_sn_)>(
          reinterpret_cast<char*>(&next_pdcp_tx_sn_),
          reinterpret_cast<char*>(&other->next_pdcp_tx_sn_));
}

::PROTOBUF_NAMESPACE_ID::Metadata pdcp_lte_state_t::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pdcp_rrc
}  // namespace fs
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::fs::pdcp_rrc::pdcp_lte_state_t* Arena::CreateMaybeMessage< ::fs::pdcp_rrc::pdcp_lte_state_t >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fs::pdcp_rrc::pdcp_lte_state_t >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
